export { default as Cart } from "./Cart/Cart";
export { default as Product } from "./Product/Product";
export { default as CategoriesMenu } from "./CategoriesMenu/CategoriesMenu";
export { default as Categories } from "./Categories/Categories";
export { default as ProductDetails } from "./ProductDetails/ProductDetails";
export { default as Favorites } from "./Favorites/Favorites";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Footer } from "./Footer/Footer";
export { default as SearchBar } from "./SearchBar/SearchBar";
